name: Pixel natsumerinchan


on:

    workflow_dispatch:
      inputs:
        RELEASE_CONFIG:
          description: 'Upload to Releases'
          required: true
          default: true
          type: boolean
        KERNEL_SOURCE:
          description: 'Kernel Source'
          required: true
          default: "https://github.com/natsumerinchan/kernel_oneplus_martini.git"
          type: string
        KERNEL_SOURCE_BRANCH:
          description: 'kernel Branch'
          required: true
          default: "thirteen"
          type: string
        KERNEL_DEFCONFIG:
          description: 'Kernel Config'
          required: true
          default: "vendor/lahaina-qgki_defconfig"
          type: string
        KERNELSU_CONFIG:
          description: 'Compile KernelSU'
          required: true
          default: true
          type: boolean
        CCACHE_CONFIG:
          description: 'Use Ccache'
          required: true
          default: true
